package com.gchofficial.iptvs.player

/**
 * Exactly one layer consumed by a system/remote Back press.
 *
 * [QuickListBack] is the odd rung out: it is not a layer this side can close,
 * only one to report. Dart owns the quick list's mode stack (`schedule` →
 * `channels` → `categories` → closed), so the Activity answers it by sending
 * `zap:back` and lets Dart decide which of those four the press meant.
 */
enum class PlayerBackAction { QuickListBack, CloseMenu, CloseInfo, HideControls, Exit }

/**
 * Pure Back-ladder policy shared by key and gesture navigation.
 *
 * Keeping this decision outside Compose focus handling prevents one remote key
 * from being interpreted once by a focused control and again by the Activity.
 *
 * **There is one rung above this ladder, and it is deliberately not here.** A
 * half-typed channel number is cleared by Back before any layer is peeled, and
 * that decision lives in [ZapKeyPolicy] because it is only reachable through
 * *key* dispatch — a gesture Back has no digit buffer behind it, and a second
 * copy of the rung here would then peel two layers for one press on the key
 * path. `HdrPlayerActivity.dispatchKeyEvent` consults [ZapKeyPolicy] first and
 * returns before `handleSystemBack` runs, so this function still describes the
 * whole ladder from the moment there is no number to clear. Don't add a
 * `ClearDigits` action to it.
 *
 * **The quick list, by contrast, *is* on this ladder** ([quickListOpen], its
 * top rung), and the difference is exactly the one above: a gesture Back with
 * the list open has something visible to close, so leaving it out would make
 * the list uncloseable on a phone using gesture navigation. There is still no
 * double peel on the key path — [ZapKeyPolicy] claims Back outright while the
 * list is open, so `handleSystemBack` never runs for that press.
 */
fun nextPlayerBackAction(
    menuOpen: Boolean,
    infoOpen: Boolean,
    controlsVisible: Boolean,
    quickListOpen: Boolean = false,
): PlayerBackAction = when {
    quickListOpen -> PlayerBackAction.QuickListBack
    menuOpen -> PlayerBackAction.CloseMenu
    infoOpen -> PlayerBackAction.CloseInfo
    controlsVisible -> PlayerBackAction.HideControls
    else -> PlayerBackAction.Exit
}

/**
 * Rejects duplicate callbacks generated by one physical Back press.
 *
 * Some Android TV images route Back through both key dispatch and the system
 * Back dispatcher. The short window is below a deliberate double-press but
 * long enough to collapse those same-press callbacks.
 */
class PlayerBackGuard(private val duplicateWindowMs: Long = 120L) {
    private var lastHandledAtMs: Long? = null

    fun shouldHandle(nowMs: Long): Boolean {
        val previous = lastHandledAtMs
        if (previous != null && nowMs - previous < duplicateWindowMs) return false
        lastHandledAtMs = nowMs
        return true
    }
}
