package com.gchofficial.iptvs.player

/** Exactly one layer consumed by a system/remote Back press. */
enum class PlayerBackAction { CloseMenu, CloseInfo, HideControls, Exit }

/**
 * Pure Back-ladder policy shared by key and gesture navigation.
 *
 * Keeping this decision outside Compose focus handling prevents one remote key
 * from being interpreted once by a focused control and again by the Activity.
 */
fun nextPlayerBackAction(
    menuOpen: Boolean,
    infoOpen: Boolean,
    controlsVisible: Boolean,
): PlayerBackAction = when {
    menuOpen -> PlayerBackAction.CloseMenu
    infoOpen -> PlayerBackAction.CloseInfo
    controlsVisible -> PlayerBackAction.HideControls
    else -> PlayerBackAction.Exit
}

/**
 * Rejects duplicate callbacks generated by one physical Back press.
 *
 * Some Android TV images route Back through both key dispatch and the system
 * Back dispatcher. The short window is below a deliberate double-press but
 * long enough to collapse those same-press callbacks.
 */
class PlayerBackGuard(private val duplicateWindowMs: Long = 120L) {
    private var lastHandledAtMs: Long? = null

    fun shouldHandle(nowMs: Long): Boolean {
        val previous = lastHandledAtMs
        if (previous != null && nowMs - previous < duplicateWindowMs) return false
        lastHandledAtMs = nowMs
        return true
    }
}
