// ignore_for_file: avoid_print, unnecessary_non_null_assertion
//
// Generator for test/fixtures/crypto_vectors.json — the cross-language interop
// gate shared with the panel's Node tests. Run:
//
//   dart run test/tool/gen_crypto_vectors.dart > test/fixtures/crypto_vectors.json
//
// It (a) validates the pure-Dart primitives against PUBLISHED known-answer
// vectors (RFC 7914 PBKDF2, RFC 5869 HKDF, NIST/McGrew AES-256-GCM, RFC 5903
// P-256 ECDH) — the run aborts if any published KAT disagrees — and (b) emits
// self-describing vectors (including self-generated end-to-end envelope cases)
// whose "expected" values are produced BY this Dart implementation, so a byte
// mismatch on the panel side is a real interop bug.

import 'dart:convert';
import 'dart:typed_data';

import 'package:iptvs/data/cloud_crypto.dart';

String hex(List<int> b) =>
    b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

Uint8List unhex(String s) {
  final out = Uint8List(s.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(s.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

void check(String label, String got, String want) {
  if (got.toLowerCase() != want.toLowerCase()) {
    stderrThrow('KAT MISMATCH [$label]\n  got : $got\n  want: $want');
  }
}

Never stderrThrow(String m) => throw StateError(m);

Future<void> main() async {
  final out = <String, dynamic>{};
  out['_note'] =
      'Cross-language crypto interop vectors for iptvs cloud E2EE. Binary is '
      'hex here; on the wire binary envelope fields are standard base64 (padded). '
      'Generated by test/tool/gen_crypto_vectors.dart from lib/data/cloud_crypto.dart.';

  // ── canonical JSON ─────────────────────────────────────────────────────────
  final canonInput = {'b': '2', 'a': '1', 'z': 'pässword→€'};
  out['canonicalJson'] = [
    {
      'name': 'sorted-keys-nonascii',
      'source': 'self (definition of canonical JSON)',
      'input': canonInput,
      'expected': canonicalJson(canonInput),
    },
  ];

  // ── PBKDF2-HMAC-SHA256 ─────────────────────────────────────────────────────
  final pbkdf2 = <Map<String, dynamic>>[];
  {
    // RFC 7914 §11 published vector (c=1).
    final want =
        '55ac046e56e3089fec1691c22544b605f94185216dde0465e68b9d57c20dacbc'
        '49ca9cccf179b645991664b39d77ef317c71b845b1e30bd509112041d3a19783';
    final got = await pbkdf2Sha256(
      utf8.encode('passwd'),
      utf8.encode('salt'),
      1,
      64,
    );
    check('pbkdf2 rfc7914 c=1', hex(got), want);
    pbkdf2.add({
      'name': 'rfc7914-passwd-salt-c1',
      'source': 'RFC 7914 §11',
      'password_utf8': 'passwd',
      'salt_utf8': 'salt',
      'iterations': 1,
      'dkLen': 64,
      'expected_hex': hex(got),
    });
  }
  {
    // RFC 7914 §11 published vector (c=80000).
    final want =
        '4ddcd8f60b98be21830cee5ef22701f9641a4418d04c0414aeff08876b34ab56'
        'a1d425a1225833549adb841b51c9b3176a272bdebba1d078478f62b397f33c8d';
    final got = await pbkdf2Sha256(
      utf8.encode('Password'),
      utf8.encode('NaCl'),
      80000,
      64,
    );
    check('pbkdf2 rfc7914 c=80000', hex(got), want);
    pbkdf2.add({
      'name': 'rfc7914-Password-NaCl-c80000',
      'source': 'RFC 7914 §11',
      'password_utf8': 'Password',
      'salt_utf8': 'NaCl',
      'iterations': 80000,
      'dkLen': 64,
      'expected_hex': hex(got),
    });
  }
  {
    // Self-generated production-parameter case (600000 iterations, 32-byte KEK).
    final salt = unhex('000102030405060708090a0b0c0d0e0f');
    final got = await pbkdf2Sha256(
      utf8.encode('iptvs-pbkdf2-selftest'),
      salt,
      kPbkdf2ProductionIterations,
      32,
    );
    pbkdf2.add({
      'name': 'self-production-c600000',
      'source': 'self-generated (production iteration count)',
      'password_utf8': 'iptvs-pbkdf2-selftest',
      'salt_hex': hex(salt),
      'iterations': kPbkdf2ProductionIterations,
      'dkLen': 32,
      'expected_hex': hex(got),
    });
  }
  out['pbkdf2HmacSha256'] = pbkdf2;

  // ── HKDF-SHA256 (RFC 5869 cases 1–3) ───────────────────────────────────────
  final hkdf = <Map<String, dynamic>>[];
  Future<void> hkdfCase(
    String name,
    String ikm,
    String salt,
    String info,
    int len,
    String want,
  ) async {
    final got = await hkdfSha256(unhex(ikm), unhex(salt), unhex(info), len);
    check('hkdf $name', hex(got), want);
    hkdf.add({
      'name': name,
      'source': 'RFC 5869 Appendix A',
      'ikm_hex': ikm,
      'salt_hex': salt,
      'info_hex': info,
      'length': len,
      'okm_hex': hex(got),
    });
  }

  await hkdfCase(
    'rfc5869-case1',
    '0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b',
    '000102030405060708090a0b0c',
    'f0f1f2f3f4f5f6f7f8f9',
    42,
    '3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf'
        '34007208d5b887185865',
  );
  await hkdfCase(
    'rfc5869-case2',
    '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f'
        '202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f'
        '404142434445464748494a4b4c4d4e4f',
    '606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f'
        '808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f'
        'a0a1a2a3a4a5a6a7a8a9aaabacadaeaf',
    'b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecf'
        'd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeef'
        'f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff',
    82,
    'b11e398dc80327a1c8e7f78c596a49344f012eda2d4efad8a050cc4c19afa97c'
        '59045a99cac7827271cb41c65e590e09da3275600c2f09b8367793a9aca3db71'
        'cc30c58179ec3e87c14c01d5c1f3434f1d87',
  );
  await hkdfCase(
    'rfc5869-case3',
    '0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b',
    '',
    '',
    42,
    '8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d'
        '9d201395faa4b61a96c8',
  );
  out['hkdfSha256'] = hkdf;

  // ── AES-256-GCM (NIST/McGrew known vectors) ────────────────────────────────
  final gcm = <Map<String, dynamic>>[];
  Future<void> gcmCase(
    String name,
    String source,
    String key,
    String iv,
    String aad,
    String pt,
    String wantCt,
    String wantTag,
  ) async {
    final ctAndTag = await aesGcmEncrypt(
      unhex(key),
      unhex(iv),
      unhex(pt),
      unhex(aad),
    );
    final ct = hex(ctAndTag.sublist(0, ctAndTag.length - 16));
    final tag = hex(ctAndTag.sublist(ctAndTag.length - 16));
    check('gcm $name ct', ct, wantCt);
    check('gcm $name tag', tag, wantTag);
    gcm.add({
      'name': name,
      'source': source,
      'key_hex': key,
      'iv_hex': iv,
      'aad_hex': aad,
      'plaintext_hex': pt,
      'ciphertext_hex': ct,
      'tag_hex': tag,
    });
  }

  await gcmCase(
    'nist-256-empty-pt',
    'McGrew/Viega GCM Test Case 13 (NIST GCM validation)',
    '0000000000000000000000000000000000000000000000000000000000000000',
    '000000000000000000000000',
    '',
    '',
    '',
    '530f8afbc74536b9a963b4f1c4cb738b',
  );
  await gcmCase(
    'nist-256-zero-block',
    'McGrew/Viega GCM Test Case 14 (NIST GCM validation)',
    '0000000000000000000000000000000000000000000000000000000000000000',
    '000000000000000000000000',
    '',
    '00000000000000000000000000000000',
    'cea7403d4d606b6e074ec5d3baf39d18',
    'd0d1c8a799996bf0265b98b5d48ab919',
  );
  // A self-generated case exercising a non-empty AAD (the envelope path).
  {
    final key = unhex(
      '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f',
    );
    final iv = unhex('101112131415161718191a1b');
    final aad = utf8.encode('iptvs.secret.v1|source|profile|src|1');
    final pt = utf8.encode('hello aad');
    final ctAndTag = await aesGcmEncrypt(key, iv, pt, aad);
    gcm.add({
      'name': 'self-with-aad',
      'source': 'self-generated (exercises non-empty AAD)',
      'key_hex': hex(key),
      'iv_hex': hex(iv),
      'aad_hex': hex(aad),
      'plaintext_hex': hex(pt),
      'ciphertext_hex': hex(ctAndTag.sublist(0, ctAndTag.length - 16)),
      'tag_hex': hex(ctAndTag.sublist(ctAndTag.length - 16)),
    });
  }
  out['aesGcm256'] = gcm;

  // ── ECDH P-256 ─────────────────────────────────────────────────────────────
  final ecdh = <Map<String, dynamic>>[];
  {
    // RFC 5903 §8.1 published vector.
    const i =
        'c88f01f510d9ac3f70a292daa2316de544e9aab8afe84049c62a9c57862d1433';
    const gix =
        'dad0b65394221cf9b051e1feca5787d098dfe637fc90b9ef945d0c3772581180';
    const giy =
        '5271a0461cdb8252d61f1c456fa3e59ab1f45b33accf5f58389e0577b8990bb3';
    const grx =
        'd12dfb5289c8d4f81208b70270398c342296970a0bccb74c736fc7554494bf63';
    const gry =
        '56fbf3ca366cc23e8157854c13c58d6aac23f046ada30f8353e74f33039872ab';
    const shared =
        'd6840f6b42f6edafd13116e0e12565202fef8e9ece7dce03812464d04b9442de';
    // Validate keypair derivation and ECDH both directions.
    final pubI = p256KeyPairFromScalar(unhex(i)).publicKey;
    check('rfc5903 pubI', hex(pubI), '04$gix$giy');
    final peerR = unhex('04$grx$gry');
    final sharedX = ecdhSharedX(unhex(i), peerR);
    check('rfc5903 shared', hex(sharedX), shared);
    ecdh.add({
      'name': 'rfc5903-p256',
      'source': 'RFC 5903 §8.1',
      'privateKey_hex': i,
      'peerPublicKey_hex': '04$grx$gry',
      'sharedX_hex': hex(sharedX),
    });
  }
  {
    // Leading-zero shared-X case: fix a device key pair, sweep an ephemeral
    // scalar until the shared X has a 0x00 leading byte.
    final device = p256KeyPairFromScalar(
      unhex('00000000000000000000000000000000000000000000000000000000000000a1'),
    );
    Uint8List? sharedX;
    String? ephHex;
    for (var s = 2; s < 4000; s++) {
      final scalar = unhex(s.toRadixString(16).padLeft(64, '0'));
      final x = ecdhSharedX(scalar, device.publicKey);
      if (x[0] == 0x00) {
        sharedX = x;
        ephHex = hex(scalar);
        break;
      }
    }
    if (sharedX == null) stderrThrow('no leading-zero shared X found in sweep');
    // Cross-check symmetry: device_priv · eph_pub == eph_priv · device_pub.
    final ephPub = p256KeyPairFromScalar(unhex(ephHex!)).publicKey;
    final other = ecdhSharedX(device.privateKey, ephPub);
    check('leadingzero symmetry', hex(other), hex(sharedX!));
    if (sharedX[0] != 0x00) stderrThrow('leading byte not zero');
    ecdh.add({
      'name': 'leading-zero-shared-x',
      'source': 'self-generated (shared X has a leading 0x00 byte)',
      'privateKey_hex': ephHex,
      'peerPublicKey_hex': hex(device.publicKey),
      'sharedX_hex': hex(sharedX),
      'note': 'sharedX_hex is exactly 32 bytes; first byte is 00 and must be '
          'preserved (left-padded), not trimmed.',
    });
  }
  out['ecdhP256'] = ecdh;

  // ── device-wrapped CK (end-to-end) ─────────────────────────────────────────
  {
    const profileId = '11111111-1111-4111-8111-111111111111';
    const deviceUid = '22222222-2222-4222-8222-222222222222';
    const ckVersion = 3;
    final ck = unhex(
      '404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f',
    );
    final devScalar = unhex(
      '00000000000000000000000000000000000000000000000000000000000000b2',
    );
    final device = p256KeyPairFromScalar(devScalar);
    final ephScalar = unhex(
      '0000000000000000000000000000000000000000000000000000000000000c3d',
    );
    final iv = unhex('303132333435363738393a3b');
    final aad = deviceWrapAad(profileId, deviceUid, ckVersion);
    final envelope = await encodeDeviceWrap(
      contentKey: ck,
      ckVersion: ckVersion,
      ephemeralPrivateKey: ephScalar,
      devicePublicKey: device.publicKey,
      iv: iv,
      aad: aad,
    );
    // Round-trip with the device private key.
    final unwrapped = await decodeDeviceWrap(
      envelope: envelope,
      devicePrivateKey: device.privateKey,
      ckVersion: ckVersion,
      aad: aad,
    );
    check('devicewrap roundtrip', hex(unwrapped), hex(ck));
    out['deviceWrap'] = [
      {
        'name': 'device-wrap-e2e',
        'source': 'self-generated (fixed eph scalar + device keypair)',
        'profileId': profileId,
        'deviceUid': deviceUid,
        'ckVersion': ckVersion,
        'contentKey_hex': hex(ck),
        'devicePrivateKey_hex': hex(device.privateKey),
        'devicePublicKey_hex': hex(device.publicKey),
        'ephemeralPrivateKey_hex': hex(ephScalar),
        'iv_hex': hex(iv),
        'aad_utf8': utf8.decode(aad),
        'envelope': envelope,
      },
    ];
  }

  // ── secret envelope (format 1, non-ASCII secret value) ─────────────────────
  {
    const profileId = '11111111-1111-4111-8111-111111111111';
    const sourceId = '33333333-3333-4333-8333-333333333333';
    const ckVersion = 3;
    final ck = unhex(
      '606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f',
    );
    final iv = unhex('0b0c0d0e0f1011121314151f');
    final secret = {'password': 'pässword→€', 'username': 'alice'};
    final aad = sourceSecretAad(profileId, sourceId, ckVersion);
    final envelope = await encryptSecretEnvelope(
      secret: secret,
      contentKey: ck,
      ckVersion: ckVersion,
      aad: aad,
      iv: iv,
    );
    final back = await decryptSecretEnvelope(
      envelope: envelope,
      contentKey: ck,
      ckVersion: ckVersion,
      aad: aad,
    );
    check('secret roundtrip pw', back['password']!, 'pässword→€');
    out['secretEnvelope'] = [
      {
        'name': 'secret-envelope-nonascii',
        'source': 'self-generated (non-ASCII secret value; canonical-JSON/UTF-8 '
            'parity)',
        'profileId': profileId,
        'sourceId': sourceId,
        'ckVersion': ckVersion,
        'contentKey_hex': hex(ck),
        'iv_hex': hex(iv),
        'secret': secret,
        'canonicalPlaintext': canonicalJson(secret),
        'aad_utf8': utf8.decode(aad),
        'envelope': envelope,
      },
    ];
  }

  // ── CK-under-KEK (panel-side; completeness) ────────────────────────────────
  {
    const profileId = '11111111-1111-4111-8111-111111111111';
    const ckVersion = 3;
    final ck = unhex(
      '808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f',
    );
    final salt = unhex('a0a1a2a3a4a5a6a7a8a9aaabacadaeaf');
    final iv = unhex('b0b1b2b3b4b5b6b7b8b9babb');
    const iterations = 4096; // low, for a fast fixture (production is 600000)
    final aad = kekAad(profileId, ckVersion);
    final envelope = await encodeCkUnderKek(
      contentKey: ck,
      ckVersion: ckVersion,
      passphrase: 'hunter2·café',
      salt: salt,
      iterations: iterations,
      iv: iv,
      aad: aad,
    );
    final back = await decodeCkUnderKek(
      envelope: envelope,
      passphrase: 'hunter2·café',
      ckVersion: ckVersion,
      aad: aad,
    );
    check('kek roundtrip', hex(back), hex(ck));
    out['ckUnderKek'] = [
      {
        'name': 'ck-under-kek-e2e',
        'source': 'self-generated (panel-side passphrase KEK)',
        'profileId': profileId,
        'ckVersion': ckVersion,
        'passphrase_utf8': 'hunter2·café',
        'contentKey_hex': hex(ck),
        'aad_utf8': utf8.decode(aad),
        'envelope': envelope,
      },
    ];
  }

  // Pretty-print, stable ordering.
  const encoder = JsonEncoder.withIndent('  ');
  print(encoder.convert(out));
}
